MACOSX_DEPLOYMENT_TARGET: '10.10'
python:
    - 3.9
numpy:
  - 1.20
c_compiler:
  - vs2019   # [win]
  - clang # [osx]
  - gcc  # [linux]
cxx_compiler:
  - vs2019   # [win]
  - clangxx # [osx]
  - gxx # [linux]
CONDA_BUILD_SYSROOT:
  /Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk

