MACOSX_DEPLOYMENT_TARGET: '10.10'
python:
    - 3.9
numpy:
  - 1.20
c_compiler:
  - vs2019   # [win]
  - clang # [osx]
  - gcc 
cxx_compiler:
  - vs2019   # [win]
  - clangxx # [osx]
  - gxx
CONDA_BUILD_SYSROOT:
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk

